import { person } from "./config";

export const metaInfo = {
  home: {
    title: `${person.name} | Software Engineer & Developer Portfolio`,
    description: `Welcome to ${person.name}'s official portfolio. Discover ${person.nickName.toLowerCase()}'s latest software development projects, engineering insights, and technical updates. Your go-to resource for cutting-edge software solutions.`,
    keywords: [
      person.name,
      person.nickName,
      "Varshil Patel",
      "Varshil Homepage",
      person.nickName + " Software Engineer",
      person.nickName + " Software Developer",
      person.nickName + " Portfolio",
      person.name + " Portfolio",
      person.name + " Software Engineer",
      person.name + " Software Developer",
      "Varshil Patel Portfolio",
      "Varshil Patel Software Engineer",
      "Varshil Patel Software Developer",
      "Software Draftsperson",
      "Tech Insights",
    ],
  },
  work: {
    title: `${person.name}'s Projects | Software Development Portfolio Showcase`,
    description: `Explore ${person.name}'s diverse portfolio of software development and engineering projects. See real-world applications and innovative solutions. View ${person.nickName}'s work today!`,
    keywords: [
      person.name + " Work",
      person.name + " Projects",
      person.name + " Portfolio",
      person.nickName + " Work",
      person.nickName + " Projects",
      person.nickName + " Portfolio",
      "Varshil Patel Work",
      "Varshil Patel Projects",
      "Varshil Patel Portfolio",
      "Software Draftsperson",
      "Software Projects",
      "Development Showcase",
    ],
  },
  reach: {
    title: `Contact ${person.name} | Get in Touch for Collaborations`,
    description: `Connect with ${person.name} for software development collaborations, project inquiries, or professional networking. Reach out directly and let's build something great together.`,
    keywords: [
      person.name + " Contact",
      person.name + " Reach",
      person.name + " Portfolio Contact",
      person.nickName + " Contact",
      person.nickName + " Reach",
      person.nickName + " Portfolio Contact",
      "Varshil Patel Contact",
      "Varshil Patel Reach",
      "Varshil Patel Portfolio Contact",
      "Software Draftsperson",
      "Software Engineer Contact",
      "Collaboration",
      "Professional Networking",
    ],
  },
};
